{"name": "Get file with incorrect file id", "status": "passed", "description": "\n        Проверяет, что при запросе файла с некорректным UUID API\n        возвращает ошибку 422 и корректное сообщение о валидации.\n        ", "start": 1756303895604, "stop": 1756303895610, "uuid": "888d5675-d447-4228-9d92-cb7002c52982", "historyId": "f0e4e32ce5f83acacb9e8ff7318ebd7e", "testCaseId": "f0e4e32ce5f83acacb9e8ff7318ebd7e", "fullName": "tests.files.test_files.TestFiles#test_get_file_with_incorrect_file_id", "labels": [{"name": "suite", "value": "Files"}, {"name": "epic", "value": "LMS service"}, {"name": "parentSuite", "value": "LMS service"}, {"name": "tag", "value": "REGRESSION"}, {"name": "story", "value": "Validate entity"}, {"name": "tag", "value": "VALIDATE_ENTITY"}, {"name": "tag", "value": "FILES"}, {"name": "subSuite", "value": "Validate entity"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Files"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "files"}, {"name": "host", "value": "MacBook-Air-Daniil.local"}, {"name": "thread", "value": "63997-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.files.test_files"}], "titlePath": ["tests", "files", "test_files.py", "TestFiles"]}